# This file is used to store the configuration of the site.

title: "Shadokos Wiki"
description: "UNIX-like zig kernel documentation"

url: "https://shadokos.github.io"
baseurl:
repository: shadokos/shadokos.github.io

# Theme settings
breadcrumb_separator: "»"
breadcrumb_font_size: 1.25rem

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-github-metadata

collections_dir: ./wiki

collections:
  dummy:
    output: true
    directory: ./wiki/_dummy
    permalink: /wiki/:path/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: "text"

google:
  cx: c3ad9401b6e094684
  site_verification: EqtKYUkYs-JttF6_8XsoKWZod8Qc2F4jvv3krniYebE
